import type { Job } from "@/types/db";

// Fallback mock data — used when Supabase env vars are not configured.
// Once Supabase is wired up, the loaders below try the DB first and fall back here.
export const MOCK_JOBS: Job[] = [
  {
    id: "m1",
    slug: "housekeeper-orlando-hilton",
    title: "Housekeeper",
    employer: "Hilton Orlando",
    category: "hospitality",
    employment_type: "full_time",
    location_city: "Orlando",
    location_state: "FL",
    hourly_rate_min: 16,
    hourly_rate_max: 19,
    description: "Daily room cleaning and guest service at a 4-star resort hotel.",
    requirements: "Reliable, attention to detail, prior cleaning experience preferred.",
    benefits: "Health insurance after 60 days, employee meal program.",
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "m2",
    slug: "construction-laborer-austin",
    title: "Construction Laborer",
    employer: "Westlake Builders",
    category: "construction",
    employment_type: "full_time",
    location_city: "Austin",
    location_state: "TX",
    hourly_rate_min: 20,
    hourly_rate_max: 24,
    description: "General site labor on residential and light commercial projects.",
    requirements: "Able to lift 50 lbs, OSHA-10 a plus.",
    benefits: "Weekly pay, overtime available.",
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "m3",
    slug: "warehouse-picker-atlanta",
    title: "Warehouse Picker",
    employer: "Peach State Logistics",
    category: "logistics",
    employment_type: "full_time",
    location_city: "Atlanta",
    location_state: "GA",
    hourly_rate_min: 17,
    hourly_rate_max: 19,
    description: "Pick and pack orders in climate-controlled facility.",
    requirements: "Forklift certification a plus but not required.",
    benefits: "Free shuttle from MARTA.",
    active: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "m4",
    slug: "apple-picker-yakima",
    title: "Apple Picker",
    employer: "Yakima Orchards Co-op",
    category: "agriculture",
    employment_type: "seasonal",
    location_city: "Yakima",
    location_state: "WA",
    hourly_rate_min: 18,
    hourly_rate_max: 22,
    description: "Seasonal apple harvest, August through October.",
    requirements: "Outdoor work, comfortable ladders.",
    benefits: "On-site housing available.",
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "m5",
    slug: "line-cook-las-vegas",
    title: "Line Cook",
    employer: "Desert Palms Resort",
    category: "hospitality",
    employment_type: "full_time",
    location_city: "Las Vegas",
    location_state: "NV",
    hourly_rate_min: 21,
    hourly_rate_max: 25,
    description: "Lunch and dinner service on the line at a busy resort restaurant.",
    requirements: "2+ years line cook experience.",
    benefits: "Tipped pool, meals on shift.",
    active: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "m6",
    slug: "cdl-driver-dallas",
    title: "CDL-A Driver (Regional)",
    employer: "Lone Star Freight",
    category: "logistics",
    employment_type: "full_time",
    location_city: "Dallas",
    location_state: "TX",
    hourly_rate_min: 26,
    hourly_rate_max: 32,
    description: "Regional routes, home weekends.",
    requirements: "Valid CDL-A, 12 months experience.",
    benefits: "Health, dental, vision, 401k match.",
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "m7",
    slug: "janitor-tampa-clearwave",
    title: "Commercial Janitor (Night)",
    employer: "ClearWave Facility Services",
    category: "cleaning",
    employment_type: "full_time",
    location_city: "Tampa",
    location_state: "FL",
    hourly_rate_min: 17,
    hourly_rate_max: 20,
    description: "Nightly cleaning of office buildings — vacuuming, restrooms, trash, common areas.",
    requirements: "Reliable, able to lift 25 lbs, valid ID for E-Verify.",
    benefits: "Paid weekly, uniforms provided.",
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "m8",
    slug: "restoration-tech-houston",
    title: "Water Damage Restoration Tech",
    employer: "GulfCoast Restoration",
    category: "restoration",
    employment_type: "full_time",
    location_city: "Houston",
    location_state: "TX",
    hourly_rate_min: 22,
    hourly_rate_max: 28,
    description: "Emergency water/fire damage cleanup, drying, demolition. On-call rotation.",
    requirements: "Valid driver's license, IICRC WRT a plus, willing to be on-call.",
    benefits: "On-call pay, company truck, OT after 40 hrs.",
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "m9",
    slug: "housekeeper-miami-marriott",
    title: "Hotel Housekeeper",
    employer: "Marriott South Beach",
    category: "hospitality",
    employment_type: "full_time",
    location_city: "Miami Beach",
    location_state: "FL",
    hourly_rate_min: 18,
    hourly_rate_max: 21,
    description: "Daily room cleaning at oceanfront hotel.",
    requirements: "Prior hotel housekeeping a plus.",
    benefits: "Free parking, employee discount on rooms.",
    active: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "m10",
    slug: "fire-restoration-dallas",
    title: "Fire Damage Restoration Tech",
    employer: "BlueLine Restoration",
    category: "restoration",
    employment_type: "full_time",
    location_city: "Dallas",
    location_state: "TX",
    hourly_rate_min: 24,
    hourly_rate_max: 30,
    description: "Soot/smoke remediation and structural drying after fire events.",
    requirements: "IICRC FSRT preferred.",
    benefits: "OT after 40, company truck.",
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "m11",
    slug: "mold-remediation-orlando",
    title: "Mold Remediation Specialist",
    employer: "GulfCoast Restoration",
    category: "restoration",
    employment_type: "full_time",
    location_city: "Orlando",
    location_state: "FL",
    hourly_rate_min: 23,
    hourly_rate_max: 28,
    description: "Containment, removal, and clearance testing of mold-impacted areas.",
    requirements: "IICRC AMRT helpful, respirator fit testing provided.",
    benefits: "Yearly safety bonus.",
    active: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "m12",
    slug: "cleaner-orlando-clearwave",
    title: "Day Porter",
    employer: "ClearWave Facility Services",
    category: "cleaning",
    employment_type: "full_time",
    location_city: "Orlando",
    location_state: "FL",
    hourly_rate_min: 16,
    hourly_rate_max: 18,
    description: "Daytime building maintenance and cleaning rounds for office complexes.",
    requirements: "Reliable, friendly.",
    benefits: "Health benefits after 90 days.",
    active: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "m13",
    slug: "prep-cook-tampa",
    title: "Prep Cook",
    employer: "Bayshore Catering Group",
    category: "food",
    employment_type: "full_time",
    location_city: "Tampa",
    location_state: "FL",
    hourly_rate_min: 18,
    hourly_rate_max: 22,
    description: "Prep work for high-volume corporate catering.",
    requirements: "1+ year kitchen experience.",
    benefits: "Shift meal, no late nights.",
    active: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "m14",
    slug: "forklift-orlando",
    title: "Forklift Operator",
    employer: "Peach State Logistics",
    category: "logistics",
    employment_type: "full_time",
    location_city: "Orlando",
    location_state: "FL",
    hourly_rate_min: 19,
    hourly_rate_max: 22,
    description: "Stand-up + sit-down forklift operation in distribution center.",
    requirements: "Valid forklift certification.",
    benefits: "Climate-controlled facility.",
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "m15",
    slug: "drywall-finisher-houston",
    title: "Drywall Finisher",
    employer: "Westlake Builders",
    category: "construction",
    employment_type: "full_time",
    location_city: "Houston",
    location_state: "TX",
    hourly_rate_min: 23,
    hourly_rate_max: 27,
    description: "Tape, mud and finish residential remodels.",
    requirements: "3+ years finishing experience.",
    benefits: "Weekly pay.",
    active: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "m16",
    slug: "carpenter-helper-austin",
    title: "Carpenter Helper",
    employer: "Westlake Builders",
    category: "construction",
    employment_type: "full_time",
    location_city: "Austin",
    location_state: "TX",
    hourly_rate_min: 20,
    hourly_rate_max: 24,
    description: "Assist lead carpenters with framing and trim.",
    requirements: "Reliable, willing to learn.",
    benefits: "Weekly pay, OT.",
    active: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
];
